print("######## SIMPLE CALCULATOR #########")
print("Enter first number")
num1 = int(input())
print("Enter Second number")
num2 = int(input())

print("Sum is ", num1+num2)
print("Multiplication is ", num1*num2)
print("Division is ", num1/num2)
print("Subtraction is ", num1-num2)